spring:
  application:
    name: course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/course
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true

server:
  compression:
    enabled: true
  port: 8181
  servlet:
    context-path: /courses
  forward-headers-strategy: framework
