server:
  compression:
    enabled: true
  servlet:
    context-path: /ead-course
  forward-headers-strategy: framework

spring:
  application:
    name: ead-course-service
  datasource:
    url: ${ead.database.url}
    username: ${ead.database.username}
    password: ${ead.database.password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    addresses: ${ead.broker.connection.address}